- name: delete master node
  os_server:
    name: master
    state: absent
    wait: yes
- name: delete worker
  os_server:
    name: worker
    state: absent
    wait: yes
- name: delete custom security group
  os_security_group:
    state: absent
    name: ccm-security-group
- name: delete router for the private network
  os_router:
    state: absent
    name: ccm-private-router
- name: delete private subnet for the private network
  os_subnet:
    state: absent
    name: ccm-private-subnet
- name: delete private network for the host VM
  os_network:
    state: absent
    name: ccm-private-net
- name: delete image
  os_image:
    name: centos8-stream
    state: absent
- name: delete local login scripts
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "login-master.sh"
    - "login-worker.sh"
